In [2]:
import numpy as np

In [7]:
numbers = np.arange(1,19,2)

numbers

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17])

In [9]:
# reshape function
matrix = numbers.reshape(3,3)
matrix

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17]])

In [12]:
### Some operations

In [21]:
mat1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
mat1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
mat2 = np.copy(mat1)

#Matrix addition
mat1 + mat2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [23]:
#Matrix substractions
mat1 - mat2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [24]:
#Matrix multiplications
mat1 * mat2

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [25]:
#Matrix Inverse
1/mat1

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667],
       [0.14285714, 0.125     , 0.11111111]])

In [26]:
print(mat1.shape)
print(mat1.ndim)
print(type(mat1))

(3, 3)
2
<class 'numpy.ndarray'>


In [27]:
import numpy as np

In [28]:
numbers = np.arange(1,10)

numbers

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
#sum of all number

numbers.sum()

45

In [30]:
#Find minimum value

numbers.min()

1

In [31]:
#Find maximum value

numbers.max()

9

In [32]:
#Find mean value

numbers.mean()

5.0

In [34]:
#Find standard deviation value

numbers.std()

2.581988897471611