In [1]:
import numpy as np

scalar_var = 10


In [3]:
vector_array = np.array([1,2,3])
print(vector_array)

[1 2 3]


In [4]:
matrix_array = np.array([[1,2,3],[4,5,6]])
print(matrix_array)

[[1 2 3]
 [4 5 6]]


In [5]:
type(matrix_array)

numpy.ndarray

In [6]:
#shape of a variable
matrix_array.shape


(2, 3)